# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Is trusted dev?

on:
  pull_request_target:

jobs:
  is-trusted-dev:
    runs-on: ubuntu-latest
    steps:
    # Generate a GitHub App installation access token from an App ID and private key
    # To create a new GitHub App:
    #   https://developer.github.com/apps/building-github-apps/creating-a-github-app/
    # See app.yml for an example app manifest
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      env: 
        SECRET: "${{ secrets.PRIVATE_KEY }}" 
      with: 
        app_id: ${{ secrets.APP_ID }}
        private_key: "${{ env.SECRET}}"

    - name: Check if Author is a trusted dev
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |

        curl -H "Authorization: token ${{ env.TOKEN}}" https://api.github.com//repos/flying-seals/action-test/collaborators/${{ github.event.pull_request.user.login }}
        

    #- name: Send ok-to-test event
    #  uses: peter-evans/repository-dispatch@v1
    #  env:
    #    TOKEN: ${{ steps.generate_token.outputs.token }}
    #  with:
    #    token: ${{ env.TOKEN }} # GitHub App installation access token
    #    event-type: ok-to-test
    #    named-args: true
    #    permission: write
